// Fichas técnicas dos fornecedores de controle de acesso/portaria remota (ONE PORTARIA e SIAM),
// destiladas dos datasheets e manuais oficiais deles (Drive dos fornecedores, set/2026). Cada ficha
// só entra no prompt de auditoria quando o NOME de algum item do orçamento bater com `match` — o
// modelo gratuito tem contexto pequeno, então não dá pra mandar tudo sempre. Só fatos lidos nos
// documentos; ao mudar/estender, mantenha o rótulo do fornecedor no texto ("ONE:" / "SIAM:").
const EQUIPMENT_KNOWLEDGE = [
  // ---------- ONE PORTARIA ----------
  { match: /c[oó]rtex|endpoint|one\s*portaria/i, text: 'ONE (portaria remota/autogerenciada): uma central Córtex + endpoints ligados por rede (precisa de switch). Todo endpoint precisa de fonte 12V (plug P4). Leitor Wiegand só liga em Endpoint 4 Portas ou FULL; Multi-IO, Sound e AquaMonitor não têm porta Wiegand. Endpoints 4 Portas/FULL/Multi-IO/Sound são compatíveis com Córtex 4 e 5. Fechadura/eletroímã liga no relé do endpoint (eletroímã no NF, trava elétrica no NA) com fonte própria — o relé só comuta. Portão pivotante/deslizante/basculante usa o Receptor FULL.' },
  { match: /c[oó]rtex|endpoint|one\s*portaria/i, text: 'ONE (guia de instalação oficial): cabo de leitor Wiegand blindado com no máximo 30 m; ligar cada dispositivo direto no switch/roteador (não cascatear); fontes SEPARADAS para faciais, eletroímãs e endpoints (nunca uma fonte só para todos os endpoints); link de no mínimo 30 Mbps de upload e download, com redundância, e VPN entre o condomínio e a base de monitoramento; equipamento em área externa com IP66 (botoeira de uso interno não vai em área externa); nobreak e baterias dimensionados para a carga total; só equipamentos homologados pela ONE (lista no Blog de Equipamentos da ONE).' },
  { match: /c[oó]rtex|endpoint|one\s*portaria/i, text: 'ONE (planos comerciais do SERVIÇO de portaria remota — é escopo de venda, NÃO exigência técnica de compatibilidade entre equipamentos: um leitor facial/controladora de acesso não exige câmera, por exemplo. Nem todo orçamento precisa de tudo; só aponte falta se o orçamento pretende ser uma portaria remota completa): todos os planos trazem câmeras Full HD, transmissão de dados com redundância, baterias e nobreak para portas e portões, alerta de portão aberto (sensor), notificação de carona, controle remoto veicular e botoeira de saída. Do plano intermediário em diante: leitura facial. Avançado/completo: portas sociais motorizadas, link redundante, interfone de elevador, monitoramento de caixa d\'água. Só no completo: cerca elétrica interligada, antenas veiculares, armário inteligente. Portaria autogerenciada (AG/AG Plus): câmeras Full HD, botoeira de saída, controle remoto veicular, leitura facial, interfonia via app. O hardware ONE costuma ser locado/comodato pelo afiliado, não vendido ao condomínio.' },
  { match: /c[oó]rtex\s*ag\b/i, text: 'ONE Córtex AG: só portaria AUTO-GERENCIADA, 1 condomínio, no máximo 30 endpoints e 30 leitores IP. LAN 10/100 sem PoE; fonte externa AC 100-240V -> 5V/3A. Só em locação/comodato: é normal ele constar no orçamento sem custo — NÃO aponte a presença dele como erro. Cenário: switch -> Endpoint 4 Portas -> leitores Wiegand, sensores e comandos.' },
  { match: /c[oó]rtex\s*(v\.?\s*)?5\b/i, text: 'ONE Córtex V5: LAN 10/100, fonte AC 100-240V -> 12V/5A, lê QR Code, aceita até 4 câmeras RTSP. Garantia só durante a vigência do contrato: é cedido em comodato e costuma constar no orçamento sem custo (normal, não é erro).' },
  { match: /c[oó]rtex\s*(v\.?\s*)?6\b/i, text: 'ONE Córtex V6: sucessor do V5 (display, web nova), 2GB RAM, LAN 10/100/1000, fonte AC 100-240V -> 12V/5A. Gerencia vários endpoints e vários leitores faciais online. Garantia só durante a vigência do contrato: é cedido em comodato e costuma constar no orçamento sem custo (normal, não é erro).' },
  { match: /endpoint.*4\s*portas|4\s*portas.*endpoint/i, text: 'ONE Endpoint 4 Portas: 4 portas Wiegand 26/34 bits (4 leitores), saída 12V para alimentar os leitores, 4 entradas de contato seco (sensores) e 4 relés NA/NF de 10A (o diagrama do mesmo datasheet cita 15A). Fonte P4 12V.' },
  { match: /endpoint.*full|endpoint\s*full/i, text: 'ONE Endpoint FULL: 2 portas Wiegand 26/34 bits, 8 entradas de contato seco, 4 relés NA/NF de 10A. Fonte P4 12V/5A (mais forte que os outros endpoints).' },
  { match: /multi[\s-]*io|mult[\s-]*io/i, text: 'ONE Endpoint Multi-IO: SEM Wiegand — 4 entradas de contato seco e 4 relés NA/NF de até 15A (automação de portão/motor). Fonte P4 12V.' },
  { match: /endpoint.*sound|one\s*sound/i, text: 'ONE Endpoint Sound: toca áudios (WAV, microSD 16GB) na portaria remota; saída de 8 ohms, máx 30W, então PRECISA de caixa de som. Fonte 12V.' },
  { match: /aqua\s*monitor/i, text: 'ONE Endpoint AquaMonitor: monitora caixa d\'água. 2 relés (bombas, máx 15A), sonda hidrostática 0-100% (sinal 0-10V, vendida à parte do endpoint), 3 entradas para sensores (temperatura, umidade, vibração, corrente). Ethernet ou Wi-Fi. Fonte P4 12V/2A.' },
  { match: /mesa\s*(de\s*)?cadastro/i, text: 'ONE Mesa de Cadastro USB: cadastra tags RFID 13MHz (Mifare) e 125MHz e controles remotos RF 433,92MHz (Linear, Citrox CX-7421, PPA ZAP 2 e 4). Conexão USB (Windows/Linux/iOS). É ferramenta de cadastro, 1 por operação, não por portaria.' },
  { match: /receptor.*433|433.*receptor|(receptor|receptora|recpetora)\s*full/i, text: 'ONE Receptor 433 (Delay/FULL): recebe controles remotos 433,92MHz e entrega Wiegand 26 bits (liga no Endpoint 4 Portas/FULL); alcance ~40m; 12V; 1 unidade atende vários portões. O FULL tem antena externa, limitação de frequência, code learning e delay p/ Nice.' },
  { match: /f(alt|alh)a\s*(de\s*)?energia/i, text: 'ONE Sensor de Falha de Energia: entrada 110/220V, saída contato seco (NF com energia, NA sem). Deve ser ligado direto na rede elétrica, nunca depois do nobreak (senão não detecta a falta).' },

  // ---------- SIAM ----------
  { match: /idbm|\bras\b|siam/i, text: 'SIAM (rede RAS): a central iDBM+ comanda um barramento RAS de dispositivos (controladoras, leitoras de expansão, sensores IMU, atuadores). O manual dá 55-65 dispositivos como limite absoluto e avisa problemas acima de 50 — não passar de ~50 por iDBM+. Cabo recomendado: cobre 0,5mm (CCI 4/6 vias ou UTP CAT5e). Distância máx. do cabo cai com a quantidade de dispositivos: 5 disp = ~190m, 10 = ~95m, 15 = ~63m, 20 = ~47m.' },
  { match: /protetor\s*ras|protetor\s*de\s*linha/i, text: 'SIAM Protetor RAS: protege só a comunicação RAS (não a fonte). Duas saídas protegidas, máx 15 dispositivos por saída; acima de 30 dispositivos exige outro protetor. Indicado quando o cabo RAS sai do painel da iDBM+.' },
  { match: /ptsm|multiplicador|testador\s*ras/i, text: 'SIAM Multiplicador PTSM-6: distribui a alimentação/RAS a vários dispositivos, corrente máx 10A na entrada. Testador RAS: ferramenta de instalação (não é item por obra).' },
  { match: /\bliva\b|cubieboard|servidor\s*siam/i, text: 'SIAM Servidor (mini PC Ubuntu, linhas LIVA/Cubieboard): guarda todo o sistema WSSIAM; cada servidor LIVA atende até 4 iDBM+. Fonte 12V/3A (LIVA X, X2, Concordia) ou 19V/3,42A (LIVA Z, ZE, ZA) — fontes diferentes, não intercambiáveis.' },
  { match: /1p4l|controladora\s*ras/i, text: 'SIAM Controladora RAS 1P4L: controle de acesso de portas/portões com leitoras Wiegand (RFID, senha, biometria); leitoras QR Code e controle remoto entram pela expansão. Até 30.000 chaves, 7.000 usuários e 16 dispositivos simultâneos. Precisa estar na rede RAS (iDBM+).' },
  { match: /ip\s*controller|\bipc\b|dual\s*gate|dualgate/i, text: 'SIAM IP Controller (IPC, RS485): até 65.000 chaves/usuários; aceita leitoras SIAM, Wiegand e integradas via API (RFID, senha, biometria, facial, QR). Dual Gate é EXPANSÃO da IPC (2 gateif, não funciona sozinha; até 8 dispositivos IPC/Dual Gate). Manuais marcados "em desenvolvimento".' },
  { match: /i12o2/i, text: 'SIAM I12O2: filho da IPC via RS485; até 24 sensores (12 zonas duplas) e 2 cargas de até 4A. Configuração só via Postman por enquanto (produto em desenvolvimento).' },
  { match: /i8o2|i802/i, text: 'SIAM i8O2: 2 relés + 8 entradas de zona dupla. Como central de alarme: até 16 sensores em até 4 partições, evento via Contact ID. O firmware é diferente por função — i8O2 de catraca NÃO substitui i8O2 de automação (e vice-versa).' },
  { match: /bruson|digicon|\bfoca\b|alianza|1cxl|stile/i, text: 'SIAM Catracas: a SIAM não fabrica a catraca, integra as de mercado (Digicon Catrax Plus, Bruson, Foca com placa FC-150, Alianza) com controladora 1CXL ou i8O2 Stile + leitoras. Se a catraca já tem placa de comando (ex.: Digicon) a integração é diferente da catraca sem placa (Bruson sem CPU Lite).' },
  { match: /controladora\s*(de\s*)?elevador/i, text: 'SIAM Controladora de Elevador: PCI instalada dentro do painel do elevador, liga nas teclas (chaves ópticas) para limitar os andares por usuário — exige abrir o painel do elevador (serviço de instalação).' },
  { match: /discador/i, text: 'SIAM Discador CID: backup de envio Contact-ID para a central de monitoramento por linha telefônica ou rádio/GPRS. Só funciona com receptores que usam CID (SIGMA, MONI, IRIS).' },
  { match: /\b(q101|le[\s-]?170|kr00\d|r00\d|c00\d)\b/i, text: 'SIAM Leitoras: Q101 e LE 170 são UHF passivo 900MHz (veicular; Q101 até 4m, LE 170 até 12m; Wiegand 26/34, 12V) — acima de 3m de cabo na Q101 usar fonte auxiliar. KR00x = RFID+senha IP68 (área externa); R00x = RFID econômica IP65; C00x = leitoras de controle remoto (alcance 80-100m). Todas usadas com controladora SIAM.' },
  { match: /\bimu\b|imee|no-?break\s*monitor|interface\s*sensor\s*de\s*tens/i, text: 'SIAM Sensores da rede RAS: IMU Discreto (2 sensores NF/NA), IMU Inundação (sonda de água), IMU Tensão (110/220V, avisa falta de energia), IMEE Monofásico (medição de energia), No-Break Monitor (monitora nobreak: 2 tensões DC + rede AC).' },
  { match: /atuador\s*(rel[eé]|triac)|\b1a1r\b/i, text: 'SIAM Atuadores (rede RAS): Atuador Relé 1A1R (motores, bombas, lâmpadas de maior potência) e Atuador TRIAC (só lâmpadas em corrente alternada).' },
];

function relevantKnowledge(items) {
  const names = items.map((i) => i.name);
  return EQUIPMENT_KNOWLEDGE.filter((k) => names.some((n) => k.match.test(n))).map((k) => `- ${k.text}`).join('\n');
}

module.exports = { EQUIPMENT_KNOWLEDGE, relevantKnowledge };
